### ISSUE TITLE
Test - Start Charging

### ISSUE THREAD

**Issue by ThorinEk** [knowitrickard/FlexiCharge-Cross-Platform#130]
Write a Widget test for the following app flow:

1. Launch
2. Register -> (Already have an account)
3. Log in
4. Home (map)
5. Chargers near me (bottom sheet)
6. Input Charger ID
7. Select Klarna payment method
8. End of flow since Klarna can / should not be tested

**Comment by Magoulo** [comment]
Requires fake mock HTTP client since the usual HTTP client is replaced.  Testing not suitable at the moment.
