### ISSUE TITLE
Test - Register & Setup Invoice

### ISSUE THREAD

**Issue by ThorinEk** [knowitrickard/FlexiCharge-Cross-Platform#132]
Write a Widget test for the following app flow:

1. Lanch
2. Register (new user)
3. Verify account
4. Home
5. Chargers near me
6. Select invoice payment method
7. Setup invoicing

**Comment by Magoulo** [comment]
Requires fake mock HTTP client since the usual HTTP client is replaced.  Testing not suitable at the moment.
